version: '3.8'

services:
  webscanner:
    build: .
    container_name: web-security-scanner
    ports:
      - "5000:5000"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webscanner.rule=Host(`scanner.localhost`)"
      - "traefik.http.services.webscanner.loadbalancer.server.port=5000"

  # Version avec image du registry GitHub
  webscanner-registry:
    image: ghcr.io/your-username/your-repo:latest
    container_name: web-security-scanner-registry
    ports:
      - "5001:5000"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - FLASK_ENV=production
    restart: unless-stopped
    profiles:
      - registry
