# Configuration pour GitHub Container Registry
# Ce fichier contient les métadonnées pour l'image Docker

name: web-security-scanner
description: "Web Security Scanner with modern web interface"
version: "1.0.0"
maintainer: "Web Security Scanner Team"
license: "MIT"

# Métadonnées Docker
labels:
  - "org.opencontainers.image.title=Web Security Scanner"
  - "org.opencontainers.image.description=Modern web security scanner with Flask interface"
  - "org.opencontainers.image.version=1.0.0"
  - "org.opencontainers.image.vendor=Web Security Scanner Team"
  - "org.opencontainers.image.licenses=MIT"
  - "org.opencontainers.image.url=https://github.com/your-username/web-security-scanner"
  - "org.opencontainers.image.source=https://github.com/your-username/web-security-scanner"
  - "org.opencontainers.image.documentation=https://github.com/your-username/web-security-scanner#readme"

# Ports exposés
expose:
  - "5000"

# Variables d'environnement
environment:
  - "HOST=0.0.0.0"
  - "PORT=5000"
  - "FLASK_ENV=production"

# Health check
healthcheck:
  test: ["CMD", "curl", "-f", "http://localhost:5000/"]
  interval: "30s"
  timeout: "10s"
  retries: 3
  start_period: "40s"
