name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract version
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ steps.version.outputs.VERSION }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.version.outputs.VERSION }}
        body: |
          ## 🚀 Web Security Scanner ${{ steps.version.outputs.VERSION }}
          
          ### 🐳 Docker Image
          ```bash
          docker pull ghcr.io/${{ github.repository }}:${{ steps.version.outputs.VERSION }}
          docker run -p 5000:5000 ghcr.io/${{ github.repository }}:${{ steps.version.outputs.VERSION }}
          ```
          
          ### 📋 Features
          - Interface web moderne et responsive
          - Analyse de sécurité complète
          - Rapports HTML détaillés
          - Support multi-architecture (AMD64, ARM64)
          
          ### 🔧 Usage
          - **Interface web**: http://localhost:5000
          - **Docker Compose**: `docker-compose up`
          - **Script de déploiement**: `./deploy.sh`
        draft: false
        prerelease: false
